name: Life Server

on:
  schedule:
    #- cron: '*/5 * * * *'

jobs:
  send-request:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request
        run: |
          curl https://jupyter-server-5v5w74p95jg3pg5w-8080.preview.app.github.dev/
